config/routes.rb
Rails.application.routes.draw do
  root to: 'profiles#index'
  resources :movies do
    get 'search', to: 'movies#search', on: :collection
  end
  resources :profiles
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :profile

  enum status: [:to_watch, :watched]

  validates :title, :api_id, presence: true
end

# quais são os valores que poderá receber de forma nomeada, por baixo dos panos ele utiliza o indice como referencia para o valor que será salvo no banco. Ele cria um método
# https://api.rubyonrails.org/v5.2.3/classes/ActiveRecord/Enum.html

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar

  validates :name, presence: true
  validate :validate_profile_quantity

  private

  def validate_profile_quantity
    profile_quantity = Profile.where(user_id: user_id).size
    errors.add(:base, :profile_quantity, message: "Quantidade de perfis excedida") if profile_quantity >= 4
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @profile = Profile.find(params[:profile_id])
    @movies = Movie.where(profile_id: @profile.id)
  end

  def search
    busca = RestClient.get 'https://api.themoviedb.org/3/search/movie', { params: { api_key: '9dfb9439b9b75b6bfb4562a044d050ba', query: params[:filme] } }

    @profile_id = params[:profile_id]
    
    @movies = JSON.parse(busca.body)
      
  end

  # listar db do model => model.all
  def create
    @movie = Movie.find_by(api_id: movie_params[:api_id])
    if @movie
      @movie.update(movie_params)
    else
      @movie = Movie.new(movie_params)
      @movie.save
    end
    @profile = Profile.find(params[:profile_id])
    flash.now[:notice] = "Salvo com sucesso."
  end

  def destroy
    Movie.delete(params[:id])
    if Movie.delete(params[:id])
      flash[:notice] = "Filme deletado com sucesso"
      redirect_to movies_path(profile_id: params[:profile_id])
    end
  end

  private

  def movie_params
    permitted = params.permit(:title,:original_language,:overview,:popularity,:poster_path,:adult,:id,:release_date, :profile_id, :status)
    permitted.tap do |p|
      p[:popularity] = p[:popularity] if p[:popularity]
      p[:api_id] = p["id"]
      p.delete(:id)
      p[:release_at] = p["release_date"] if p["release_date"] 
      p.delete(:release_date)
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.where({user_id:current_user.id})
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to profiles_path
    else 
      flash.now[:alert] = "Dados inválidos"
      render(:new)
    end
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def destroy
    Profile.delete(params[:id])
    redirect_to profiles_path
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :avatar).merge({user_id:current_user.id})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def exibir_poster(poster_path)
    if poster_path
      "https://image.tmdb.org/t/p/original/#{poster_path}"
    else
      'https://www.joblo.com/assets/images/joblo/database-specific-img-225x333.jpg'
    end

  end
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type == "alert" ? "danger" : "success"%> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListFilmsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">List Movies</a>
      <%= link_to 'Sign out', destroy_user_session_path, class: 'btn btn-dark', method: :delete if current_user %>
    </nav>
    
    <div class="flash-message">
      <%= render 'layouts/flash' %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/create.js.erb
var assistir = document.querySelector(".assistir")
var assistido = document.querySelector(".assistido")

  $(".movie-<%= @movie.id%>").remove()
  var html = `
  <div class="card movie-<%= @movie.id%>" style="width: 18rem; margin: 6px;">
    <img src="<%= exibir_poster(@movie.poster_path)%>" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title btn btn-light" data-toggle="modal" data-target="#exampleModal"><%= @movie.title%></h5>
      <p class="card-text"> <%= @movie.overview%></p>
      <%= link_to 'Deletar da lista', movie_path(id: @movie.id,profile_id: @profile.id), class: 'btn btn-dark float-right', method: :delete %>

      <%= link_to 'Assistido', movies_path(profile_id: @movie.id, id: @movie.api_id, profile_id: @profile.id, status: "watched"), class: 'btn btn-warning', method: :post, 'data-remote': true  if @movie.to_watch? %> 
    </div>
  </div>
  `
  <% if @movie.to_watch? %>
    assistir.innerHTML += html
  <% else %>
    assistido.innerHTML += html
  <% end %>
  
  <%# j para ter o html puro scape javascript e por html safe, partial %>
  var flashHtml = "<%= j render 'layouts/flash' %>"
  var flashMessage = document.querySelector('.flash-message')

  flashMessage.innerHTML = flashHtml

app/views/movies/index.html.erb
<h1> Olá, <%= @profile.name %>!</h1>

<%= link_to 'Voltar', root_path, method: :get, class: 'button is-light' %>

<%= link_to 'Deletar perfil', profile_path(@profile.id), class: 'btn btn-dark float-right', method: :delete %>

 </br></br>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#busca">Buscar</a>
  </li>

  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#assistido">Assistidos</a>
  </li>

  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#assistir">Assistir</a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">

  <div class="tab-pane fade show active" id="busca" role="tabpanel">
    <%= form_with url:  search_movies_path, method: :get  do |form|%>
    <!-- input escondido com o nome :profile_id que passa como valor o id do perfil (utilizar quando quer passar algo e não mostrar na tela) -->
      <%= form.hidden_field :profile_id, value: @profile.id %>
      <div class="input-group mb-3">
        <%= form.text_field :filme, class:'form-control', placeholder: 'Buscar filmes', 'aria-label': 'Buscar filmes' %>
        <div class="input-group-append">
          <button class="btn btn-outline-primary" type="submit">Buscar</button>
        </div>
      </div>
    <% end %>
    <div class="resultado row justify-content-center">
    </div>
  </div>


  <div class="tab-pane fade" id="assistido" role="tabpanel">        
    <div class="row justify-content-center assistido">
       <% @movies.select(&:watched?).each do |movie| %>

      <div class="card movie-<%=movie.id%>" style="width: 18rem; margin: 6px;">
        <img src="<%= exibir_poster(movie.poster_path)%>" class="card-img-top" alt="...">
          <div class="card-body">
          <h5 class="card-title btn btn-light" data-toggle="modal" data-target="#exampleModal"><%= movie.title%></h5>
          <p class="card-text"><%= movie.overview%></p>
          <%= link_to 'Deletar da lista', movie_path(id: movie.id,profile_id: @profile.id), class: 'btn btn-dark float-right', method: :delete %>
        </div>
      </div>
     <%end%>
      
    </div>
  </div>

  <div class="tab-pane fade" id="assistir" role="tabpanel" aria-labelledby="contact-tab">
  <div class="row justify-content-center assistir">
     <% @movies.select(&:to_watch?).each do |movie| %>

      <div class="card movie-<%= movie.id%>" style="width: 18rem; margin: 6px;">
        <img src="<%= exibir_poster(movie.poster_path)%>" class="card-img-top" alt="...">
          <div class="card-body">
          <h5 class="card-title btn btn-light" data-toggle="modal" data-target="#exampleModal"><%= movie.title%></h5>
          <p class="card-text"><%= movie.overview%></p>
          <%= link_to 'Deletar da lista', movie_path(id: movie.id,profile_id: @profile.id), class: 'btn btn-dark float-right', method: :delete %>

          <%= link_to 'Assistido', movies_path(profile_id: movie.id, id: movie.api_id, profile_id: @profile_id, status: "watched"), class: 'btn btn-warning', method: :post, 'data-remote': true  %>
        </div>
      </div>
     <%end%>
  </div>
  
  <div>
  
</div>

app/views/movies/search.js.erb
var resultado = document.querySelector(".resultado")
var img = "https://www.joblo.com/assets/images/joblo/database-specific-img-225x333.jpg"

var movies = ""
<% @movies['results'].each do |item| %>
    var cadaFilme = <%= raw item.to_json %>
    console.log(cadaFilme)
    
  var html = `
  <div class="card" style="width: 18rem; margin: 6px;">
    <img src="<%= exibir_poster(item["poster_path"])%>" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title btn btn-light" data-toggle="modal" data-target="#exampleModal-<%= item["id"]%>">${cadaFilme.title}</h5>
      <p class="card-text">${cadaFilme.overview}</p>
    </div>
  </div>
    
  <div class="modal fade" id="exampleModal-<%= item["id"]%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">

          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
            <strong><%= item["title"]%></strong></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <p><strong> Idioma Original: </strong> <%= item["original_language"] %></p>
            <p><strong> Data de lançamento: </strong><%= item["release_date"]%></p>
            <p><strong> Popularidade: </strong><%= item["popularity"]%></p>
            <p><strong> Resumo:</strong> <%= item["overview"]%> </p>
          </div>

          <div class="modal-footer">
            <%= link_to 'Assistir', movies_path(params: item.merge(profile_id: @profile_id, status: "to_watch")), class:'btn btn-success', method: :post, 'data-remote': true  %>
            <%= link_to 'Assistido', movies_path(params: item.merge(profile_id: @profile_id, status: "watched")), class: 'btn btn-warning', method: :post, 'data-remote': true  %>
          </div>

        </div>
      </div>
  </div>
  `

  movies += html
<% end %>

resultado.innerHTML = movies

app/views/movies/watch.js.erb
var assistir = document.querySelector(".assistir")

var watchMovie = <%= raw @movie.to_json %>
    
  var html = `
  <div class="card" style="width: 18rem; margin: 6px;">
    <img src="<%= exibir_poster(@movie["poster_path"])%>" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title btn btn-light" data-toggle="modal" data-target="#exampleModal">${watchMovie.title}</h5>
      <p class="card-text">${watchMovie.overview}</p>
    </div>
  </div>
  `
  assistir.innerHTML += html    

app/views/profiles/index.html.erb
<h1> Bem vindo!!! </h1>

</br></br>

<div class="row justify-content-center">
  <% @profiles.each do |profile| %>
    <div class="card col-md-3 ml-2">
      <%= link_to movies_path({profile_id:profile.id}) do %>
      <% if profile.avatar.attached? %>
        <%=image_tag profile.avatar,class:'card-img-top', style:'width: 100%; margin-top:10px' %>
      <% else %>
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png" style="width: 100%; margin-top:10px">
      <%end%>
        <div class="card-body">
          <p class="card-text"><%= profile.name %></p>
        </div>
      <% end %>
    </div>
    </br></br>
  <% end %>
</div>

</br></br>

<%= link_to 'Criar perfil', new_profile_path, class: 'btn btn-success', method: :get %>

app/views/profiles/new.html.erb
<%if @profile.errors.present? %> <p class="alert alert-secondary" role="alert"><%= @profile.errors.full_messages.first%> </p>
<%end%>

<%= form_with model: @profile, local: true do |form| %>
  <div class="form-group">
  <%= form.label 'Inserir avatar (opcional)', style:'font-size: 20px' %>:
  <%= form.file_field :avatar, class:'form-control-file', style:'margin: 10px' %>
  <%= form.label 'Insira o nome do perfil', style:'font-size: 20px'%>:
  <%= form.text_field :name, class:'form-control', style:'margin: 10px'%>
  <%= form.submit 'Criar', class:'btn btn-primary'%> 
<% end%>


<%= link_to 'Voltar', root_path, method: :get, class: 'button is-light' %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>